# Generated by Django 4.0.1 on 2022-03-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100, unique=True)),
                ('activity_type', models.CharField(max_length=100, unique=True)),
                ('activity_date', models.DateField()),
                ('activity_time', models.DateTimeField()),
                ('activity_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_mail', models.CharField(max_length=500, unique=True)),
                ('admin_password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Meditate',
            fields=[
                ('med_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=50, unique=True)),
                ('med_description', models.CharField(max_length=50, unique=True)),
                ('med_imgurl', models.URLField()),
                ('med_songurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('pub_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pub_type', models.CharField(default='text', max_length=6)),
                ('pub_date', models.DateField(auto_now=True)),
                ('pub_title', models.CharField(max_length=100)),
                ('pub_description', models.TextField(max_length=500)),
                ('pub_url', models.URLField(max_length=500)),
                ('suggestion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('song_url', models.URLField()),
                ('song_singer', models.CharField(max_length=50)),
                ('song_type', models.CharField(default='sleep', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('st_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('st_date', models.DateField()),
                ('st_nb_user', models.IntegerField()),
                ('st_nb_pub', models.IntegerField()),
                ('st_nb_sugg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_mail', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=50)),
                ('user_Lastname', models.CharField(max_length=50)),
                ('user_date_birth', models.DateField()),
                ('user_dateOfJoin', models.DateField(auto_now=True)),
                ('user_avatar', models.ImageField(blank=True, default='', upload_to='')),
                ('user_type', models.CharField(max_length=40)),
                ('user_objectifs', models.CharField(max_length=500)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_message', models.TextField(max_length=500, unique=True)),
                ('report_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
                ('report_pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_author', to='pcd.user'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_reactions',
            field=models.ManyToManyField(blank=True, default=[], related_name='pub_reactions', to='pcd.User'),
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('pl_id', models.AutoField(primary_key=True, serialize=False)),
                ('pl_name', models.CharField(max_length=50, unique=True)),
                ('pl_imgurl', models.URLField()),
                ('songs', models.ManyToManyField(blank=True, default=[], related_name='playliste_song', to='pcd.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(max_length=500, unique=True)),
                ('plan_activity', models.ManyToManyField(default=[], related_name='plan_activity', to='pcd.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_content', models.TextField(max_length=500)),
                ('note_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField(max_length=500, unique=True)),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.user')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcd.publication')),
            ],
        ),
    ]
