# Generated by Django 4.0.1 on 2022-01-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_mail', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_last_name', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_mail', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=20)),
                ('DateOfJoining', models.DateField()),
                ('user_password', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
