# Generated by Django 4.0.1 on 2022-01-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0002_admin_user_delete_departments_delete_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=0.0004948045522018803, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_mail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.CharField(max_length=500),
        ),
    ]
